const TEMPLATES = {
    signup: {
        subject: "Welcome!",
        html: '<!DOCTYPE html>        <html>        <head>          <title>Welcome to our platform!</title>          <style>            /* Inline CSS styles */            body {              font-family: Arial, sans-serif;              font-size: 16px;              line-height: 1.4;              color: #333;              background-color: #f4f4f4;              padding: 0;              margin: 0;            }            .container {              max-width: 600px;              margin: 0 auto;              padding: 20px;              background-color: #fff;              border-radius: 5px;              box-shadow: 0 0 10px rgba(0,0,0,.1);            }            h1 {              font-size: 24px;              margin-top: 0;              color: #333;            }            p {              margin-bottom: 20px;            }            .btn {              display: inline-block;              background-color: #007bff;              color: #fff;              font-size: 16px;              padding: 10px 20px;              text-decoration: none;              border-radius: 5px;              margin-bottom: 20px;            }          </style>        </head>        <body>          <div class="container">            <h1>Welcome to our platform!</h1>            <p>Dear <%= name %>,</p>            <p>Thank you for joining our platform. We are excited to have you as a member of our community!</p>            <p>With our platform, you can:</p>            <ul>              <li>Connect with other users</li>              <li>Share your ideas and experiences</li>              <li>Learn new things</li>            </ul>            <p>We hope you enjoy your experience on our platform. If you have any questions or feedback, please feel free to reach out to us at <a href="mailto:contact@ourplatform.com">contact@ourplatform.com</a>.</p>            <p>Best regards,<br>The Our Platform Team</p>            <a href="<%= link %>" class="btn">Get Started</a>          </div>        </body>        </html>'
    },
    resetPassword: {
        subject: "Reset your Password",
        html: `<!DOCTYPE html><html><head>  <meta charset="UTF-8">  <title>Password Reset Link</title>  <style>    /* Inline CSS */    .button {      background-color: #4CAF50;      border: none;      color: white;      padding: 12px 28px;      text-align: center;      text-decoration: none;      display: inline-block;      font-size: 16px;      margin-bottom: 16px;      cursor: pointer;      border-radius: 8px;    }  </style></head><body>  <p>Hi <%= name %>,</p>  <p>We have received a request to reset your password. To reset your password, please click on the button below:</p>  <a href="<%= resetLink %>" target="_blank" ><button class="button">Reset Password</button></a>  <p>If the button above does not work, please copy and paste the following URL into your web browser:</p>  <p><%= resetLink %></p>  <p>This link is only valid for 15 mins.</p>  <p>If you didn't request this, please ignore.</p>  <p>Thank you</p></body></html>`
    },
    addUserByAdmin: {
        subject: "Welcome to UnoForms.xyz",
        html: `<!DOCTYPE html><html><head><style type="text/css">@import url(https://fonts.googleapis.com/css2?family=Lobster&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap);body{font-family:Poppins,sans-serif}.header{font-family:Lobster,cursive;font-size:36px;text-align:center;margin-bottom:20px}.button{display:inline-block;background-color:#007bff;color:#fff;padding:10px 20px;border-radius:5px;text-decoration:none;margin-bottom:20px}.fallback{margin-bottom:20px}</style></head><body><div class="header"><h1>UnoForms</h1></div><p>Dear <%= name %>,</p><p>Welcome to Unoforms! We're excited to have you on board.</p><p>To set up your account, please click the link below to generate a password:</p><p class="fallback"><a href="<%= passwordLink %>" target="_blank"><%= passwordLink %> </a></p><p>Please note that the link is only valid for 7 days.</p><p>If you have any questions or need assistance, please don't hesitate to contact us at support@unoforms.xyz.</p><p>Best regards,</p><p>The Unoforms Team</p></body></html>`
    },
    newFormSubmission: {
        subject: "New Form Submission",
        html: '<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial,sans-serif;margin:0;padding:0}.container{width:100%;max-width:900px;margin:0 auto;padding:20px;border:1px solid #ccc;border-radius:4px}h1{color:#333;font-size:24px;margin-bottom:10px}p{color:#555;margin-bottom:20px}table{width:100%;border-collapse:collapse;margin-bottom:20px}td,th{padding:8px;text-align:left;border-bottom:1px solid #ccc}.button-container{margin-top:20px}.button{display:inline-block;background-color:#29bcb0;color:#fff;font-weight:700;text-decoration:none;padding:10px 20px;border-radius:4px}@media only screen and (max-width:600px){.container{width:100%}}</style></head><body><table class="container" align="center" cellpadding="0" cellspacing="0"><tr><td><h1>New Form Submission</h1><p>You got a new submission for <%= form.title %></p><table><thead><tr><th>Key</th><th>Value</th></tr></thead><tbody> <% form?.formData.forEach(data => { %> <tr><td><%= data.key %></td><td><%= data.value %></td></tr> <% }) %> </tbody></table><p>To View Other Submissions, go to UnoForms Dashboard</p><div class="button-container"><a href="<%= `app.unoforms.xyz/forms/${form.id}` %>" class="button">View Dashboard</a></div></td></tr></table></body></html>'
    }
}

export default TEMPLATES;